version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: homiehotel-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hotel
      MYSQL_USER: homiehotel
      MYSQL_PASSWORD: homiehotel123
      TZ: Asia/Ho_Chi_Minh
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/hotel.sql:/docker-entrypoint-initdb.d/hotel.sql
    restart: unless-stopped
    networks:
      - homiehotel-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # HomieHotel Application
  homiehotel:
    build: .
    container_name: homiehotel-app
    ports:
      - "9596:9596"
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - JAVA_OPTS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/hotel?serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9596/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - ./logs:/app/logs
      - ./uploads:/app/uploads
    networks:
      - homiehotel-network

volumes:
  mysql_data:

networks:
  homiehotel-network:
    driver: bridge 