version: '3.8'

services:
  homiehotel:
    image: homiehotel:latest
    container_name: homiehotel-app
    ports:
      - "9596:9596"
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - JAVA_OPTS=-Xmx512m -Xms256m
      # Kết nối với MySQL từ XAMPP
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/hotel?serverTimezone=Asia/Ho_Chi_Minh
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9596/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - ./logs:/app/logs
      - ./uploads:/app/uploads
    networks:
      - homiehotel-network
    # Extra hosts để kết nối với XAMPP trên host
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  homiehotel-network:
    driver: bridge 